@startuml
class com.example.myongsubway.StationInformationFragment {
- {static} String ARG_PARAM1
- {static} String ARG_PARAM2
- String mParam1
- String mParam2
- LinearLayout buildingLayout
- LinearLayout restuarentLayout
- LinearLayout adjacentLayout
- LinearLayout facilitiesLayout
- LinearLayout lineLayout
- TextView vertexName
- TextView toilet
- TextView door
- TextView number
- TextView update
- TextView airstate
- TextView pmq
- TextView congestion
- Button reportButton
- Button closeButton
- CustomAppGraph.Vertex vertex
~ CustomAppGraph graph
- boolean isZoomPath
+ void onDestroy()
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void onClick(View)
~ void getAir()
}
class com.example.myongsubway.StationInformationFragment.AirThread {
+ void run()
}
class com.example.myongsubway.ViewHolder {
+ TextView stationTextView
}
class com.example.myongsubway.SearchAdapter {
- Context context
- LayoutInflater inflate
- List<String> stationList
- ViewHolder viewHolder
+ int getCount()
+ Object getItem(int)
+ long getItemId(int)
+ View getView(int,View,ViewGroup)
}
class com.example.myongsubway.ZoomPathFragment {
- ArrayList<Integer> path
- ArrayList<Integer> lines
- ArrayList<Integer> btnBackgrounds
- ArrayList<Integer> lineColors
- CustomAppGraph graph
~ int stationButtonWidthDpBig
~ int stationButtonWidthDpSmall
~ int stationButtonHeightDp
~ int dottedLineMarginDp
~ int dottedLineHeightDp
~ int simpleLineWidthDp
~ int simpleLineHeightDp
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void createStation(View)
- void createButton(View,int,float,int,int)
- void createButton(View,int,float,int,int,int)
- void createSimpleLine(View,int,float)
- void createTransferButton(View,int,float)
- void createLineTextViewAndButton(View,int,float,int,int)
- void createMidLayout(View,int,float)
- void createEmptyButton(View,float)
- void registerListener(View)
}
class com.example.myongsubway.CommentFragment {
- {static} String ARG_PARAM1
- {static} String ARG_PARAM2
- String mParam1
- String mParam2
~ FirebaseDatabase db
~ DatabaseReference dr
- String content
- String writer
- String time
- String boardid
- String id
- TextView commentText
- TextView writerText
- TextView timeText
- Button confirmButton
- CustomAppGraph graph
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ String getContent()
+ String getWriter()
+ String getTime()
+ String getBoardid()
+ String getCommenttId()
+ void setContent(String)
+ void setWriter(String)
+ void setTime(String)
+ void setBoardid(String)
+ void setId(String)
+ void onClick(View)
}
class com.example.myongsubway.BookmarkActivity {
- FirebaseAuth mAuth
- ListView stationList
- ListView routeList
- CustomAppGraph graph
- Context mContext
# void onCreate(Bundle)
+ boolean onOptionsItemSelected(MenuItem)
# void onResume()
}
class com.example.myongsubway.SignInActivity {
- Button signIn
- Button withoutSignIn
+ EditText email
+ EditText password
+ Button signUp
+ ArrayList<String> bookmarkedStation
+ ArrayList<String> bookmarkedRoute
+ Map<String,Object> bookmarkedMap
- FragmentManager fragmentManager
- SignUpFragment SignUpFragment
- FragmentTransaction transaction
- FirebaseAuth mAuth
+ boolean isFragment
# void onCreate(Bundle)
+ void saveSearchData()
+ void loadSearchData()
~ void setEmail(String)
~ String getEmail()
~ String getPassword()
~ void destroyFragment()
+ void onBackPressed()
}
class com.example.myongsubway.ForcedTerminationService {
+ IBinder onBind(Intent)
+ void onTaskRemoved(Intent)
}
class com.example.myongsubway.BackPressHandler {
- Activity activity
- long backPressedTime
+ void onBackPressed()
}
class com.example.myongsubway.BoardModifyActivity {
~ Button closeButton
~ Button confirmButton
~ TextView titleText
~ TextView contentText
~ CardItem item
- CustomAppGraph graph
# void onCreate(Bundle)
+ void onClick(View)
}
class com.example.myongsubway.StationReportFragment {
- {static} String ARG_PARAM1
- {static} String ARG_PARAM2
- String mParam1
- String mParam2
- LinearLayout menuLinearLayout
- LinearLayout addLinearLayout
- Button opaqueButton
- Button departureButton
- Button destinationButton
- Button closeButton
- Button informationButton
- ImageButton bookmarkButton
- Button nameButton
- Button leftButton
- Button rightButton
- Button toiletButton
- Button doorButton
- Button nameButton2
- TextView lineTextView
- ArrayList<Button> addButtonList
- CustomAppGraph.Vertex vertex
- ArrayList<CustomAppGraph.Vertex> vertices
- CustomAppGraph graph
- int line
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
+ void removeInformationFragment(StationInformationFragment)
+ void onClick(View)
}
class com.example.myongsubway.MinTimePathFragment {
~ ArrayList<Integer> minTimePath
~ ArrayList<Integer> lines
~ ArrayList<Integer> costs
~ CustomAppGraph graph
~ ArrayList<CustomAppGraph.Vertex> vertices
~ ArrayList<Integer> btnBackgrounds
~ ArrayList<Integer> lineColors
~ Button departureButton
~ ImageButton zoomButton
~ Button reportButton
~ TextView departureLine
~ TextView costTime
~ ImageView midLine
+ void onResume()
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void init(View)
- void registerListener()
- void setLineTextViewMargin()
- void setMidLineGradient()
- void setCostTextView()
- String convertTime(int)
- String convertDistance(int)
- String convertCost(int)
}
class com.example.myongsubway.SearchActivity {
- ListView stationListView
- EditText editStation
- SearchAdapter searchAdapter
- ArrayList<String> searchedStationList
- ArrayList<String> viewedStationList
- Button backButton
- CustomAppGraph graph
- ArrayList<CustomAppGraph.Vertex> vertices
- Button removeSearchHistoryButton
# void onCreate(Bundle)
+ void removeSearchHistory()
+ void search(String)
+ void addSearchedStation(String)
+ void saveSearchData()
+ void loadSearchData()
}
class com.example.myongsubway.MinDistancePathFragment {
~ ArrayList<Integer> minDistancePath
~ ArrayList<Integer> lines
~ ArrayList<Integer> costs
~ CustomAppGraph graph
~ ArrayList<CustomAppGraph.Vertex> vertices
~ ArrayList<Integer> btnBackgrounds
~ ArrayList<Integer> lineColors
~ Button departureButton
~ ImageButton zoomButton
~ Button reportButton
~ TextView departureLine
~ TextView costTime
~ ImageView midLine
+ void onResume()
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void init(View)
- void registerListener()
- void setLineTextViewMargin()
- void setMidLineGradient()
- void setCostTextView()
- String convertTime(int)
- String convertDistance(int)
- String convertCost(int)
}
class com.example.myongsubway.AccountInformationActivity {
- TextView account
- FirebaseAuth mAuth
# void onCreate(Bundle)
+ boolean onOptionsItemSelected(MenuItem)
+ void onClickSignOut(View)
+ void onCLickRevoke(View)
}
class com.example.myongsubway.TransferWalkTimeActivity {
- CustomAppGraph graph
- Button fastWalkButton
~ int START_INDEX
~ String SPAN_COLOR
~ String CLICK_COLOR
# void onCreate(Bundle)
- void init()
- void initButton()
- void setToolbar()
- void registerListener()
- void changeButtonColorSpan(Button,String)
+ boolean onOptionsItemSelected(MenuItem)
}
class com.example.myongsubway.ShortestPathActivity {
- ViewPager2 viewPager
- FragmentStateAdapter pagerAdapter
- TabLayout tabLayout
- List<String> tabElement
- String departure
- ArrayList<ArrayList<Integer>> paths
- ArrayList<ArrayList<Integer>> allCosts
- ArrayList<ArrayList<Integer>> allLines
- int TYPE_COUNT
- int TRANSFER_WEIGHT
~ int LAST_INDEX
- ImageButton setAlarmButton
- CustomAppGraph graph
- FirebaseAuth mAuth
- ArrayList<Integer> btnBackgrounds
- ArrayList<Integer> lineColors
- ImageButton bookmarkButton
- boolean isButtonClicked
- CustomAppGraph.SearchType pageType
- CustomAppGraph.SearchType buttonType
- AlarmManager alarmManager
- int registeredAlarmCount
+ {static} Context ShortestPathContext
~ int IC_NORMAL_ALARM_BUTTON
~ int IC_ANOTHER_SELECTED_ALARM_BUTTON
# void onCreate(Bundle)
- void init()
- void checkDepartureArrival()
- void initBookmarkButton()
- void initAlarmButton()
+ void finishAlarm()
- void registerAlarm()
- void startAlarm(int,int,CustomAppGraph.Vertex)
+ void cancelAlarm()
- void registerListener()
- void addBookmarkedRoute()
- void removeBookmarkedRoute()
- boolean isContained()
+ void setPageType(CustomAppGraph.SearchType)
- void setPagerAndTabLayout()
- void setToolbar()
+ boolean onOptionsItemSelected(MenuItem)
- void dijkstra(int,CustomAppGraph.SearchType)
- void getPathLines(CustomAppGraph.SearchType)
- void calculateAllCosts(ArrayList<Integer>,CustomAppGraph.SearchType,int)
- int calculateElapsed(ArrayList<Integer>,CustomAppGraph.SearchType,CustomAppGraph.SearchType)
- int calculateElapsed(CustomAppGraph.SearchType)
+ void generateStationInformationFragment(CustomAppGraph.Vertex)
+ void generateZoomPathFragment(ArrayList<Integer>,ArrayList<Integer>,CustomAppGraph.SearchType)
- void initializeBtnBackgrounds()
- void initializeLineColors()
}
class com.example.myongsubway.VertexCost {
~ int vertex
~ int cost
+ int compareTo(VertexCost)
}
class com.example.myongsubway.ShortestPathActivity.VPAdapter {
- ArrayList<Fragment> items
+ Fragment createFragment(int)
+ int getItemCount()
}
class com.example.myongsubway.BoardWatchActivity {
~ FirebaseDatabase db
~ DatabaseReference dr
+ {static} BoardAdapter adapter
~ ArrayList<CardItem> dataList
~ RecyclerView recyclerView
- FloatingActionButton writeButton
- Button watchButton
- Button resetButton
# void onCreate(Bundle)
+ void resetBoard()
+ void onItemClick(View,int)
+ void onClick(View)
+ void onResume()
}
class com.example.myongsubway.BoardAdapter {
- ArrayList<CardItem> mDataList
- Context context
- OnItemClickEventListener mItemClickListener
+ void setOnItemClickListener(OnItemClickEventListener)
+ CustomViewHolder onCreateViewHolder(ViewGroup,int)
+ void onBindViewHolder(CustomViewHolder,int)
+ int getItemCount()
+ {static} String formatTimeString(long)
}
class com.example.myongsubway.BoardAdapter.CustomViewHolder {
~ TextView title
~ TextView content
~ TextView time
~ TextView writer
~ Button commentnumber
}

class com.example.myongsubway.SignUpFragment {
- FirebaseAuth mAuth
- {static} String ARG_PARAM1
- {static} String ARG_PARAM2
- String mParam1
- String mParam2
+ EditText email
+ EditText password
+ Button complete
+ {static} SignUpFragment newInstance(String,String)
+ void onCreate(Bundle)
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
~ String getEmail()
~ String getPassword()
~ String getUserData()
+ void onDestroy()
}
class com.example.myongsubway.CustomAppGraph {
- HashMap<String,Integer> map
- HashMap<Integer,String> reverseMap
- ArrayList<Vertex> vertices
- ArrayList<ArrayList<Edge>> adjacent
- int STATION_COUNT
- int EDGE_COUNT
- String email
- String password
- ArrayList<String> bookmarkedStation
- ArrayList<String> bookmarkedRoute
- Map<String,Object> bookmarkedMap
- int LINE_COUNT
- String alarmKey
- int alarmCount
- int alarmNumForCount
+ float FAST_WALK
+ float NORMAL_WALK
+ float SLOW_WALK
- float walkSpeed
- int[] TRANSFER_DISTANCE
- int distanceIndex
- int clamp(int,int,int)
+ void setWalkSpeed(float)
+ float getWalkSpeed()
- void initWalkSpeed()
+ void onCreate()
- void createGraph()
+ boolean setAccount(String,String,ArrayList<String>,ArrayList<String>)
+ void setBookmarkedStation(ArrayList<String>)
+ void setBookmarkedRoute(ArrayList<String>)
+ void setBookmarkedMap(HashMap<String,Object>)
+ boolean isLogined()
+ void clearAccount()
+ String getEmail()
+ ArrayList<String> getBookmarkedStation()
+ ArrayList<String> getBookmarkedRoute()
+ Map<String,Object> getBookmarkedMap()
+ ArrayList<Vertex> getVertices()
+ ArrayList<ArrayList<Edge>> getAdjacent()
+ HashMap<String,Integer> getMap()
+ HashMap<Integer,String> getReverseMap()
+ int getEdgeCount()
+ int getStationCount()
+ void setAlarmKey(String)
+ void destroyAlarm()
+ void setAlarmCount(int)
+ String getAlarmKey()
+ int getAlarmCount()
+ int decreaseAlarmNum()
+ void onConfigurationChanged(Configuration)
+ void onLowMemory()
}
class com.example.myongsubway.CustomAppGraph.Edge {
- int[] edgeData
+ int getCost(SearchType)
}
class com.example.myongsubway.CustomAppGraph.Vertex {
- String vertex
- ArrayList<Integer> adjacent
- int line
- ArrayList<Integer> lines
- boolean toilet
- String number
- String doorDirection
- String[] stationFacilities
- String[] nearbyRestaurants
- String[] nearbyFacilities
- String congestion
- int transferDistance
- void addAdjacent(int)
- void addInformation(String,String,String,String,String,String)
- void addTransferDistance(int)
- void setCongestion(String)
+ String getVertex()
+ ArrayList<Integer> getAdjacent()
+ int getLine()
+ ArrayList<Integer> getLines()
+ boolean getToilet()
+ String getNumber()
+ String getDoorDirection()
+ String[] getStationFacilities()
+ String[] getNearbyRestaurants()
+ String[] getNearbyFacilities()
+ String getCongestion()
+ int getTransferDistance()
}
class com.example.myongsubway.MinCostPathFragment {
~ ArrayList<Integer> minCostPath
~ ArrayList<Integer> lines
~ ArrayList<Integer> costs
~ CustomAppGraph graph
~ ArrayList<CustomAppGraph.Vertex> vertices
~ ArrayList<Integer> btnBackgrounds
~ ArrayList<Integer> lineColors
~ Button departureButton
~ ImageButton zoomButton
~ Button reportButton
~ TextView departureLine
~ TextView costTime
~ ImageView midLine
+ void onResume()
+ View onCreateView(LayoutInflater,ViewGroup,Bundle)
- void init(View)
- void registerListener()
- void setLineTextViewMargin()
- void setMidLineGradient()
- void setCostTextView()
- String convertTime(int)
- String convertDistance(int)
- String convertCost(int)
}
class com.example.myongsubway.MainActivity {
+ {static} Context mcontext
+ StationReportFragment fragment
- Button findButton
- Button changeButton
- Button departX
- Button destiX
- Button gotoGame
- Button gotoBookmark
- Button gotoSearch
- Button gotoSetting
- Button gotoBoard
+ TextView departText
+ TextView destiText
- Intent intent
- CustomAppGraph graph
- FirebaseAuth mAuth
+ ArrayList<Button> stationButtonList
+ ArrayList<CustomAppGraph.Vertex> mainVertices
- BackPressHandler backPressHandler
- boolean isFragment
# void onCreate(Bundle)
~ void destroyFragment()
~ void launchReport(String)
+ void addBookmarkedStation(String)
+ void removeBookmarkedStation(String)
+ boolean isContained(String)
+ void onClick(View)
~ String getDepart()
~ String getDesti()
~ void setDepart(String)
~ void setDesti(String)
~ void setIsFragmentFalse()
~ void setIsFragmentTrue()
~ void setDepartInvisible()
~ void setDepartvisible()
~ void setDestiInvisible()
~ void setDestitvisible()
~ void setDepartGray()
~ void setDepartBlack()
~ void setDestiGray()
~ void setDestiBlack()
+ void onBackPressed()
}
class com.example.myongsubway.OpenSourceInfoActivity {
# void onCreate(Bundle)
+ boolean onOptionsItemSelected(MenuItem)
}
class com.example.myongsubway.UnityPlayerActivity {
# UnityPlayer mUnityPlayer
# String updateUnityCommandLineArguments(String)
# void onCreate(Bundle)
+ void receiveStr(String)
+ void onUnityPlayerUnloaded()
+ void onUnityPlayerQuitted()
# void onNewIntent(Intent)
# void onDestroy()
# void onStop()
# void onStart()
# void onPause()
# void onResume()
+ void onLowMemory()
+ void onTrimMemory(int)
+ void onConfigurationChanged(Configuration)
+ void onWindowFocusChanged(boolean)
+ boolean dispatchKeyEvent(KeyEvent)
+ boolean onKeyUp(int,KeyEvent)
+ boolean onKeyDown(int,KeyEvent)
+ boolean onTouchEvent(MotionEvent)
+ boolean onGenericMotionEvent(MotionEvent)
}
class com.example.myongsubway.SettingsActivity {
- Button accountInformation
- Button transferWalkSpeed
- CustomAppGraph graph
# void onCreate(Bundle)
+ boolean onOptionsItemSelected(MenuItem)
+ void onClickAccount(View)
+ void onclickQuestion(View)
+ void onClickTransferWalkSpeed(View)
+ void onnClickOpenSourceInfo(View)
}
class com.example.myongsubway.AlarmReceiver {
- Context mContext
- String channelId
- String channelName
+ void onReceive(Context,Intent)
}
class com.example.myongsubway.BoardReadActivity {
~ FirebaseDatabase db
~ DatabaseReference dr
~ TextView titleText
~ TextView contentText
~ TextView writerandtimeText
~ TextView commentText
~ Button commentbutton
~ Toolbar myToolbar
~ LinearLayout commentLayout
~ ArrayList<CommentFragment> commentList
~ CardItem item
- CustomAppGraph graph
- InputMethodManager imm
~ FragmentManager fragmentManager
~ FragmentTransaction fragmentTransaction
# void onCreate(Bundle)
~ void setRefresh()
~ void setCommentRefresh()
+ void onResume()
+ void onClick(View)
+ boolean onCreateOptionsMenu(Menu)
+ boolean onOptionsItemSelected(MenuItem)
}
class com.example.myongsubway.CardItem {
- String id
- String title
- String content
- String time
- String writer
- String commentnumber
+ void setTitle(String)
+ void setContent(String)
+ void setWriter(String)
+ void setTime(String)
+ void setId(String)
+ void setCommentnumber(String)
+ String getTitle()
+ String getContent()
+ String getWriter()
+ String getTime()
+ String getId()
+ String getCommentnumber()
}
class com.example.myongsubway.BoardWriteActivity {
~ Button closeButton
~ Button confirmButton
~ TextView titleText
~ TextView contentText
~ CustomAppGraph graph
# void onCreate(Bundle)
+ void onClick(View)
}


com.example.myongsubway.StationInformationFragment +.. com.example.myongsubway.StationInformationFragment.AirThread
android.app.Service <|-- com.example.myongsubway.ForcedTerminationService
com.example.myongsubway.BoardAdapter +.. com.example.myongsubway.BoardAdapter.CustomViewHolder
com.example.myongsubway.ViewHolder <|-- com.example.myongsubway.BoardAdapter.CustomViewHolder
android.app.Application <|-- com.example.myongsubway.CustomAppGraph
com.example.myongsubway.CustomAppGraph +.. com.example.myongsubway.CustomAppGraph.Edge
com.example.myongsubway.CustomAppGraph +.. com.example.myongsubway.CustomAppGraph.Vertex
com.unity3d.player.IUnityPlayerLifecycleEvents <|.. com.example.myongsubway.UnityPlayerActivity
android.app.Activity <|-- com.example.myongsubway.UnityPlayerActivity
@enduml